### create Project
Post http://localhost:3000/project/create
Authorization: Bearer {{$dotenv TOKEN}}
Content-Type: application/json

{
    "title":"salamTitle",
    "text":"salamText"
}

### get All Projects
Get http://localhost:3000/project/list
Authorization: Bearer {{$dotenv TOKEN}}

### get Project
GET http://localhost:3000/project/qwdkwqpodwqpwk
Authorization: Bearer {{$dotenv TOKEN}}

### remove Project
Delete http://localhost:3000/project/remove/qwdkwqpodwqpwk
Authorization: Bearer {{$dotenv TOKEN}}

### edit Project
Put http://localhost:3000/project/edit/apsijdapisjdspadj
Authorization: Bearer {{$dotenv TOKEN}}