### create Project
Post http://localhost:3000/project/create
Authorization: Bearer {{$dotenv TOKEN}}
Content-Type: application/json

{
    "title":"salamTitle",
    "text":"salamText"
}

### get All Projects
GET http://localhost:3000/project/list
Authorization: Bearer {{$dotenv TOKEN}}

### get Project By Id
GET http://localhost:3000/project/62d8283107907bfec43c3bc0
Authorization: Bearer {{$dotenv TOKEN}}

### remove Project
Delete http://localhost:3000/project/remove/62d8283107907bfec43c3bc0
Authorization: Bearer {{$dotenv TOKEN}}

### edit Project
Put http://localhost:3000/project/edit/apsijdapisjdspadj
Authorization: Bearer {{$dotenv TOKEN}}